function Hd = Lowpassfilter
%LOWPASSFILTER 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 29-Apr-2023 17:23:19

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 220000000;  % Sampling Frequency

Fpass = 100000000;       % Passband Frequency
Fstop = 105000000;       % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
